package detector

import (
	"math"
	"testing"

	"github.com/angch/gogcbot/pkg/db"
)

// Clean usernames (human-chosen) — must score below threshold.
var cleanUsernames = []string{
	"angch", "axslice", "azuanz", "gammarayburster", "geodome", "gmhafiz",
	"han_yuji", "iconsumebugs", "leowmjw", "mynameisnotjackiechan", "pickfire",
	"ragibkl", "realityredefined", "seventhpotato", "Sharuzzaman", "syahflutist",
	"teohhanhui", "yasaikun", "zhengqunkoo", "zypeh",
}

// Banned usernames (auto-generated/farmed) and their true UsernameAnomalyScore.
// Range: mixed-case autogen handles (uppercase_ratio >= 0.25) and lowercase
// handles with interleaved digits (digits scattered mid-string between letters).
var bannedUsernames = map[string]int{
	"UCRkGpqBYfNI":             6,
	"PgFXuyhnjILjO":            6,
	"HcVemrYaIIXdHjSYZ":        6,
	"lwbGMfQOslOWDtGUycbPEhZn": 6,
	"jatFNKQkGTMwjyciZ":        6,
	"nykrr_v9cl2t":             6,
	"rjmu5z2wpk1":              6,
	"qtdulcljcptk6950":         3,
	"xPSlxSuoacSnbuoMLxji":     3,
	"XIlIehpRYaoKr":            3,
}

// Known misses: banned handles the classifier still cannot catch — either a
// word-shaped handle with a trailing/underscore digit block (indistinguishable
// from "name_23" / "name2233") or pure natural words (south_road). These stay
// below threshold by design.
var unclassifiableBanned = map[string]int{
	"south_road": 0,
	"Rose_21re":  0,
	"Cuffy_26":   1,
}

func TestUsernameAnomalyScore_Calibration(t *testing.T) {
	for _, u := range cleanUsernames {
		if s := UsernameAnomalyScore(u); s >= 3 {
			t.Errorf("clean username %q scored %d >= 3 (false positive)", u, s)
		}
	}
	for u, want := range bannedUsernames {
		if s := UsernameAnomalyScore(u); s != want {
			t.Errorf("banned username %q scored %d, want %d", u, s, want)
		}
	}
	for u, want := range unclassifiableBanned {
		if s := UsernameAnomalyScore(u); s != want {
			t.Errorf("unclassifiable banned username %q scored %d, want %d", u, s, want)
		}
	}
}

func TestInterleavedDigits(t *testing.T) {
	tests := []struct {
		s    string
		want int
	}{
		{"nykrr_v9cl2t", 2}, // v9c, l2t
		{"rjmu5z2wpk1", 2},  // u5z, z2w
		{"Cuffy_26", 0},     // underscore before digits
		{"Rose_21re", 0},    // underscore before digits
		{"jane2233", 0},     // trailing block
		{"michael2233", 0},  // trailing block
		{"joshis_23", 0},    // underscore block
		{"angch", 0},        // no digits
		{"a1b", 1},          // single buried digit
		{"tony2fast4u", 2},  // two buried digits
		{"abc12", 0},        // trailing only
		{"12ab", 0},         // leading only
	}
	for _, tt := range tests {
		if got := interleavedDigits(tt.s); got != tt.want {
			t.Errorf("interleavedDigits(%q) = %d, want %d", tt.s, got, tt.want)
		}
	}
}

func TestShannonEntropy(t *testing.T) {
	tests := []struct {
		s    string
		want float64
	}{
		{"", 0},
		{"aaaa", 0},                // 1 unique char
		{"abab", 1.0},              // 2 eq chars
		{"qtdulcljcptk6950", 3.62}, // banned: high diversity
	}
	for _, tt := range tests {
		got := shannonEntropy(tt.s)
		if math.Abs(got-tt.want) > 0.02 {
			t.Errorf("shannonEntropy(%q) = %.3f, want %.2f", tt.s, got, tt.want)
		}
	}
}

func TestUsernameAnomalyTrigger_Evaluate(t *testing.T) {
	cfg := UsernameAnomalyTriggerConfig{
		Enabled:       true,
		MinHighUserID: 1000000000,
		MaxReputation: 5,
		MaxUserPosts:  5,
		MinScore:      3,
		FlagOnly:      true,
	}
	trig := NewUsernameAnomalyTrigger(cfg)

	tests := []struct {
		name          string
		ctx           *TriggerContext
		wantTriggered bool
	}{
		{
			name: "new high-ID user with autogenerated username",
			ctx: &TriggerContext{
				IsNewUser: true,
				User:      &db.User{UserID: 5000000000, Reputation: 0, Username: "UCRkGpqBYfNI"},
			},
			wantTriggered: true,
		},
		{
			name: "new high-ID user with human username",
			ctx: &TriggerContext{
				IsNewUser: true,
				User:      &db.User{UserID: 5000000000, Reputation: 0, Username: "angch"},
			},
			wantTriggered: false,
		},
		{
			name: "established user with many posts skipped",
			ctx: &TriggerContext{
				IsNewUser:        false,
				UserMessageCount: 15,
				User:             &db.User{UserID: 5000000000, Reputation: 0, Username: "UqRkGpqBYfNI"},
			},
			wantTriggered: false,
		},
		{
			name: "low ID user skipped",
			ctx: &TriggerContext{
				IsNewUser: true,
				User:      &db.User{UserID: 123456, Reputation: 0, Username: "UqRkGpqBYfNI"},
			},
			wantTriggered: false,
		},
		{
			name: "high rep user skipped",
			ctx: &TriggerContext{
				IsNewUser: true,
				User:      &db.User{UserID: 5000000000, Reputation: 50, Username: "UqRkGpqBYfNI"},
			},
			wantTriggered: false,
		},
		{
			name: "empty username not triggered",
			ctx: &TriggerContext{
				IsNewUser: true,
				User:      &db.User{UserID: 5000000000, Reputation: 0, Username: ""},
			},
			wantTriggered: false,
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			res, err := trig.Evaluate(tt.ctx)
			if err != nil {
				t.Fatalf("unexpected error: %v", err)
			}
			if res.Triggered != tt.wantTriggered {
				t.Fatalf("Triggered = %v, want %v (reason: %s)", res.Triggered, tt.wantTriggered, res.Reason)
			}
			// FlagOnly should emit exactly one action: flag_message.
			if res.Triggered && (len(res.Actions) != 1 || res.Actions[0].Type != ActionFlagMessage) {
				t.Errorf("FlagOnly actions wrong: %#v", res.Actions)
			}
		})
	}
}

// Regression: these common human handles must NOT trigger (score < 3). They
// used to false-positive via the removed digit/underscore/consonant-run features.
func TestUsernameAnomalyScore_NoFalsePositivesOnHumanHandles(t *testing.T) {
	human := []string{
		"joshis_23", "jane2233", "michael2233", "ryanp789", "krzysztof",
	}
	for _, u := range human {
		if s := UsernameAnomalyScore(u); s >= 3 {
			t.Errorf("human handle %q scored %d >= 3 (false positive)", u, s)
		}
	}
}

func TestUsernameAnomalyTrigger_BanMode(t *testing.T) {
	cfg := UsernameAnomalyTriggerConfig{
		Enabled:       true,
		MinHighUserID: 1000000000,
		MaxUserPosts:  5,
		MinScore:      3,
		FlagOnly:      false, // ban mode
	}
	trig := NewUsernameAnomalyTrigger(cfg)
	res, err := trig.Evaluate(&TriggerContext{
		IsNewUser: true,
		User:      &db.User{UserID: 5000000000, Reputation: 0, Username: "UqRkGpqBYfNI"},
	})
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	if !res.Triggered {
		t.Fatal("expected trigger in ban mode")
	}
	if len(res.Actions) != 4 {
		t.Fatalf("ban mode should emit 4 actions, got %d", len(res.Actions))
	}
	var hasDelete, hasBan, hasRep, hasFlag bool
	for _, a := range res.Actions {
		switch a.Type {
		case ActionDeleteMessage:
			hasDelete = true
		case ActionBanUser:
			hasBan = true
		case ActionAdjustReputation:
			hasRep = true
		case ActionFlagMessage:
			hasFlag = true
		}
	}
	if !hasDelete || !hasBan || !hasRep || !hasFlag {
		t.Errorf("ban mode actions incomplete: %#v", res.Actions)
	}
}
