package detector

import (
	"math"
	"strings"
)

// UsernameAnomalyTriggerConfig configures thresholds for the auto-generated
// username anomaly detection trigger.
type UsernameAnomalyTriggerConfig struct {
	Enabled       bool  `mapstructure:"enabled" yaml:"enabled"`
	MinHighUserID int64 `mapstructure:"min_high_user_id" yaml:"min_high_user_id"`
	MaxReputation int   `mapstructure:"max_reputation" yaml:"max_reputation"`
	MaxUserPosts  int   `mapstructure:"max_user_posts" yaml:"max_user_posts"`
	// MinScore is the anomaly score threshold above which a username triggers.
	// See UsernameAnomalyScore. Default 3.
	MinScore int `mapstructure:"min_score" yaml:"min_score"`
	// FlagOnly emits only a flag/report action instead of auto-banning.
	// Recommended true until the rule is battle-tested.
	FlagOnly   bool `mapstructure:"flag_only" yaml:"flag_only"`
	RepPenalty int  `mapstructure:"rep_penalty" yaml:"rep_penalty"`
}

// UsernameAnomalyTrigger detects brand new, high-ID, low-rep users whose
// Telegram username matches the signature of an auto-generated (spam/farmed)
// handle rather than a human-chosen one.
type UsernameAnomalyTrigger struct {
	cfg UsernameAnomalyTriggerConfig
}

// NewUsernameAnomalyTrigger constructs a new UsernameAnomalyTrigger.
func NewUsernameAnomalyTrigger(cfg UsernameAnomalyTriggerConfig) *UsernameAnomalyTrigger {
	return &UsernameAnomalyTrigger{cfg: cfg}
}

func (t *UsernameAnomalyTrigger) ID() string {
	return "username_anomaly"
}

func (t *UsernameAnomalyTrigger) Name() string {
	return "New High-ID User Auto-Generated Username Detection"
}

func (t *UsernameAnomalyTrigger) IsEnabled() bool {
	return t.cfg.Enabled
}

func (t *UsernameAnomalyTrigger) Evaluate(ctx *TriggerContext) (*TriggerResult, error) {
	if !t.IsEnabled() || !MatchesCohort(ctx, t.cfg.MinHighUserID, t.cfg.MaxReputation, t.cfg.MaxUserPosts) {
		return &TriggerResult{Triggered: false}, nil
	}

	username := strings.TrimSpace(ctx.User.Username)
	if username == "" {
		return &TriggerResult{Triggered: false}, nil
	}

	score := UsernameAnomalyScore(username)
	minScore := t.cfg.MinScore
	if minScore <= 0 {
		minScore = 3
	}
	if score < minScore {
		return &TriggerResult{Triggered: false}, nil
	}

	repPenalty := t.cfg.RepPenalty
	if repPenalty <= 0 {
		repPenalty = 20
	}

	reason := "Detection trigger (username_anomaly): High-ID new user with low/no rep has an auto-generated style username"

	actions := []Action{
		{
			Type:   ActionFlagMessage,
			Reason: reason,
		},
	}
	if !t.cfg.FlagOnly {
		actions = append(actions,
			Action{Type: ActionDeleteMessage, Reason: reason},
			Action{Type: ActionBanUser, Reason: reason},
			Action{Type: ActionAdjustReputation, RepDelta: -repPenalty, Reason: reason},
		)
	}

	return &TriggerResult{
		Triggered: true,
		TriggerID: t.ID(),
		Reason:    reason,
		Actions:   actions,
	}, nil
}

// UsernameAnomalyScore scores a Telegram username on how autogenerated it looks.
// Higher is more suspicious. Retained features, calibrated against a labeled
// set of banned (auto-generated/farmed) and clean (human-chosen) handles:
//
//	+3  uppercase_ratio >= 0.25     mixed-case autogen signature
//	+1  vowel_ratio < 0.15          vowel-starved
//	+3  interleaved digits >= 2     digits scattered mid-string between letters
//	+2  interleaved digits == 1
//	+2  entropy >= 3.4 AND          high character diversity AND vowel-starved
//	    vowel_ratio < 0.15           (catches long uniformly-random autogen)
//
// "Interleaved" means a digit block with a letter on both sides (digits buried
// in the middle of the word), as opposed to a terminal/underscore block like
// "name_23" or "name2233". Human handles put digits at the tail; autogen ones
// scatter them amid letters.
//
// The entropy term is gated on low vowel ratio specifically to avoid flagging
// long legitimate names (e.g. "gareth_lewis"), which also have high entropy but
// are vowel-rich.
func UsernameAnomalyScore(username string) int {
	if username == "" {
		return 0
	}

	var upperCount, vowelCount, totalLen int

	for _, r := range username {
		totalLen++
		switch r {
		case 'a', 'e', 'i', 'o', 'u':
			vowelCount++
		}
		if r >= 'A' && r <= 'Z' {
			upperCount++
		}
	}

	vowelRatio := 0.0
	if totalLen > 0 {
		vowelRatio = float64(vowelCount) / float64(totalLen)
	}

	score := 0
	if totalLen > 0 && float64(upperCount)/float64(totalLen) >= 0.25 {
		score += 3
	}
	if vowelRatio < vowelGateThreshold {
		score += 1
	}
	switch inter := interleavedDigits(username); {
	case inter >= 2:
		score += 3
	case inter == 1:
		score += 2
	}
	// The entropy signal: high diversity + vowel-starved isolates long,
	// uniformly-random autogen handles (e.g. "qtdulcljcptk6950").
	if shannonEntropy(username) >= entropyThreshold && vowelRatio < vowelGateThreshold {
		score += 2
	}
	return score
}

// entropyThreshold is the character-diversity cutoff for the entropy term.
const entropyThreshold = 3.4

// vowelGateThreshold gates the vowel-starved condition shared by the vowel and
// entropy terms.
const vowelGateThreshold = 0.15

// shannonEntropy computes the Shannon entropy (bits per character) of s.
func shannonEntropy(s string) float64 {
	if s == "" {
		return 0
	}
	counts := make(map[rune]int)
	totalRun := 0
	for _, r := range s {
		counts[r]++
		totalRun++
	}
	h := 0.0
	for _, c := range counts {
		p := float64(c) / float64(totalRun)
		h -= p * math.Log2(p)
	}
	return h
}

// interleavedDigits counts digit blocks that have a letter immediately on both
// sides: digits buried inside the word rather than a trailing/underscore block.
func interleavedDigits(s string) int {
	inter := 0
	n := len(s)
	isAlpha := func(c byte) bool {
		return (c >= 'a' && c <= 'z') || (c >= 'A' && c <= 'Z')
	}
	for i := 0; i < n; {
		if s[i] < '0' || s[i] > '9' {
			i++
			continue
		}
		j := i
		for j < n && s[j] >= '0' && s[j] <= '9' {
			j++
		}
		if i > 0 && j < n && isAlpha(s[i-1]) && isAlpha(s[j]) {
			inter++
		}
		i = j
	}
	return inter
}
